# Generated by Django 3.0.3 on 2020-10-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalPharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=100000, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('ven', models.CharField(blank=True, max_length=5, null=True)),
                ('unit', models.DecimalField(decimal_places=1, max_digits=100, null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=100, null=True)),
                ('planned_Qty_2Month_Mean', models.DecimalField(decimal_places=3, max_digits=100, null=True)),
                ('currentStock', models.DecimalField(decimal_places=3, default=0, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='TheDailyConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumptionDate', models.DateTimeField(auto_now_add=True)),
                ('consumptionQty', models.IntegerField()),
                ('pharmacies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.HospitalPharmacy')),
                ('productLink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ProductDetails')),
            ],
        ),
        migrations.CreateModel(
            name='StockDelivered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryDate', models.DateTimeField(auto_now_add=True)),
                ('deliveredQty', models.DecimalField(decimal_places=3, max_digits=100)),
                ('productLink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ProductDetails')),
            ],
        ),
    ]
