# Generated by Django 3.0.3 on 2020-10-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TargetUserUnit',
        ),
    ]
