# Generated by Django 3.0.3 on 2020-10-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_stockdeliverydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptiondata',
            name='pharmacies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.HospitalUserUnit'),
        ),
    ]
