# Generated by Django 3.0.3 on 2020-10-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_consumptiondata_pharmacies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdeliverydata',
            old_name='productLink',
            new_name='productDetail',
        ),
    ]
