# Generated by Django 3.0.3 on 2020-10-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20201024_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptiondata',
            name='consumptionDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
